version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: nginx.prod.dockerfile
    ports:
      - 80:80
      - 443:443
    depends_on: 
      - mysql
      - php
      - assets
  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment: 
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - ./mysql:/var/lib/mysql    
  php:
    build:
      context: .
      dockerfile: php.prod.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
  assets:
    image: node:current-alpine
    volumes:
      - ./src:/var/www/html
    command: ["/bin/sh", "-c", "npm install && npm run production"]
    #command: ["php", "/var/www/html/artisan", "migrate:refresh"]
    working_dir: /var/www/html